### ISSUE TITLE
[BD] Obtener Posiciones de Users

### ISSUE THREAD

**Issue by crilin** [rbenal/open-fixture-be#12]
- Crear SP que realice los cálculos de las apuestas hechas por los jugadores y devolver un cursor:
  a) Lista de puntaje obtenidos por los usuarios en un juego.
  b) Lista de puntaje total obtenido por los usuarios por todos los juegos finalizados.

**Comment by hladera100** [comment]
Se termina la funcion para el calculo del total de los puntos por cada usuario. GET_USER_TOTAL_POINTS
