### ISSUE TITLE
[BD] SP grupos

### ISSUE THREAD

**Issue by crilin** [rbenal/open-fixture-be#16]
- Crear una vista que contenga la información de los equipos junto al grupo que pertenece.
- Crear SP que cálcule los siguientes valores: **PG**, **PE**, **PP**, **GF**, **GC**, **DG**, **PTS**,
obtenidos por cada equipo en los juegos finalizados durante el Mundial.
- Devolver un cursor de los grupos con sus respectivos equipo junto con los valores obtenidos en los cálculos.

**Comment by hladera100** [comment]
A este SP Hice una Vista para mostrar el mismo resultado que un cursor.

**Comment by hladera100** [comment]
A este SP Hice una Vista para mostrar el mismo resultado que un cursor.
