### ISSUE TITLE
[ENDPOINT] Calendario de partidos

### ISSUE THREAD

**Issue by crilin** [rbenal/open-fixture-be#18]
- Crear **WS** que devuelva la información de los partidos obtenido de la BD.
- Obtener **GET** y generar Response tipo **JSON** con los valores:
  - /list: Lista de todos los partidos con sus equipos, fecha y hora, estadio.

**Comment by rbenal** [comment]
solved by commit 9ebaba0fdbfb35c60530caff0e52f50adb785386
