### ISSUE TITLE
La clase UserMapper no implementa la interface Imapper

### ISSUE THREAD

**Issue by crilin** [rbenal/open-fixture-be#24]
Se crea la rama bug-user-mapper-interface para adaptar la clase userMapper a la nueva arquitectura de open-fixture-be

**Comment by crilin** [comment]
Agregado todas las funciones que implementa la clase Mapper

**Comment by crilin** [comment]
Adicionalmente se agregó el Request  PUT y DELETE

**Comment by crilin** [comment]
rbenal continua con la solución del bug

**Comment by rbenal** [comment]
solved with commit aec391cb42fe0baa4efb47f6949a17e12e21ee38
