### ISSUE TITLE
Crear vista en BD de Apuestas del Dia

### ISSUE THREAD

**Issue by crilin** [rbenal/open-fixture-be#9]
Desarrollar un script de BD para generar una Vista con los siguiente estructura:

time|stadium|team_name_a|goals_team_a|team_flag_a|team_name_b|team_goals_a|team_flag_b|user_name|user_goals_team_a|user_goals_team_b
------|------|--------|-----|-----|------|-----|-----|-----|------|------
HH:MM| stadium | Argentina | 0 | flag_url | Brasil | 0 | flag_url | Nullpointer13 | 3 | 1 | status-del-partido

Notas adicionales:

* La hora debe venir en formato 24 Hrs.
* el url de las banderas debe venir de la conf. de la BD
* El nombre de usuario debe ser preferiblemente el alias
* Item 2b
* los goles de los equipos deben venir de la tabla games, hayan finalizados o no.
* los goles de las apuestas deben venir de la tabla de apuestas.
* order by HORA

**Comment by rbenal** [comment]
@hladera100  esta esta buena para comenzar

**Comment by rbenal** [comment]
solved in commit c3ccc5c9b06f84a9a8dd43be7201d7c72acdccf4
